name: 15 - Working with Matrices
on:
    workflow_dispatch:
jobs: 
    backwards-compatibility:
        name: ${{matrix.os-version}} && Node-version ${{matrix.node-version}} 
        runs-on: ${{matrix.os-version}}
        strategy:
            # fail-fast: false
            matrix:
                node-version :
                    - 18.x
                    # - 20.x
                os-version:
                    - ubuntu-latest
                    # - windows.latest
                include:
                    - os: ubuntu-latest
                      node-version: 16.x    
        steps:
            - name : setup node
              uses : actions/setup-node@v3
              with: 
                node-version: ${{matrix.node-version}}
            - name : Job deployment
              run : |
               echo " ${{matrix.os-version}} && Node-version ${{matrix.node-version}}"           
          



    